"""wiki URL

Revision ID: 0a6512d8c03e
Revises: cf689a1270db
Create Date: 2017-04-02 13:10:15.902452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a6512d8c03e'
down_revision = 'cf689a1270db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('wiki_url', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'wiki_url')
    # ### end Alembic commands ###
