"""original title

Revision ID: 410d090d227d
Revises: 8c0dadbfc97d
Create Date: 2017-03-31 22:21:38.782513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '410d090d227d'
down_revision = '8c0dadbfc97d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('original_title', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'original_title')
    # ### end Alembic commands ###
