"""Image field

Revision ID: 8c0dadbfc97d
Revises: 20ee887d2d16
Create Date: 2017-03-30 16:11:40.860511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c0dadbfc97d'
down_revision = '20ee887d2d16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('image', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'image')
    # ### end Alembic commands ###
